package:
  name: cloudmesh.common
  version: 1.0

source:
  git_url: https://github.com/cloudmesh/cloudmesh.common.git

build:
  number: 0

requirements:
  build:
    - python
    - six
    - future
    - prettytable
    - python-hostlist
    - simplejson
    - oyaml
    - colorama
    - psutil
    - hypothesis

  run:
    - python
    - six
    - future
    - prettytable
    - python-hostlist
    - simplejson
    - oyaml
    - colorama
    - psutil
    - hypothesis
