BOX = "ubuntu/xenial64"
NUMBER_OF_NODES = 1

Vagrant.configure("2") do |config|
  config.vm.define "node-1" do |nodeConfig|
    nodeConfig.vm.box = BOX
    nodeConfig.vm.network "private_network", type: "dhcp"
  end

  (2..NUMBER_OF_NODES).each do |i|
    config.vm.define "node-#{i}" do |nodeConfig|
      nodeConfig.vm.box = BOX
      nodeConfig.vm.network "private_network", type: "dhcp"
    end
  end
end
