package:
  name: cloudmesh.sys
  version: 1.0

source:
  git_url: https://github.com/cloudmesh/cloudmesh.sys.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pip
    - cloudmesh.common

  run:
    - cloudmesh.common
    - wheel
    - twine
