version: '2'

environment:
  - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "${HOME}/.cloudmesh/mongo/data:/data/db

  mongoCreateAdmin:
   image: mongo:latest
   container_name: mongoClientTemp
   links:
    - mongo:mongo
   command: mongo --host mongo --eval  "db.getSiblingDB('dashboard').createUser({user:'admin', pwd:'dbpass', roles:[{role:'readWrite',db:'dashboard'}]});"
    depends_on:
      - mongo
